language: cpp


compiler: gcc

before_install:
 - sudo add-apt-repository -y ppa:beineri/opt-qt591-trusty
 - sudo apt-get update -qq
 - sudo apt-get install qt59-meta-full
 - sudo apt-get install qt59charts-no-lgpl 
 
before_script:
  - source /opt/qt59/bin/qt59-env.sh
  - mkdir build
  - cd build
  - sh ../travis/install_charts.sh
  - cmake .. 

script: make
