environment:
  QBit_RELEASE_PATH: .
  QTDIR: C:\Qt\5.9.1\mingw53_32

install:
  - git submodule update --init --recursive
  
build_script:
  - mkdir build
  - cd build
  - cmake ..-DCMAKE_BUILD_TYPE=Release ..
  - mingw32-make 
  
#deploy:
  #release: QBit-v$(appveyor_build_version)
  #description: 'Release description'
  #provider: GitHub
  #auth_token:
    #secure: <your encrypted token> # your encrypted token from GitHub
  #artifact: /.*\.nupkg/            # upload all NuGet packages to release assets
  #draft: false
  #prerelease: false
  #on:
    #branch: master                 # release from master branch only
    #appveyor_repo_tag: true        # deploy on tag push only
