image: Visual Studio 2015

environment:
  matrix:
  - qt: C:\Qt\5.9\msvc2015_64
    PLATFORM: amd64
    COMPILER: msvc
    VSVER: 14
    
    
clone_depth: 1

init:
  - set TAG_NAME=%APPVEYOR_REPO_TAG_NAME%
  - set PATH=%qt%;%PATH%
  
build_script:
  - call "scripts/build_windows.cmd"

artifacts:
  - path: build\windows\msvc\x86_64\release\YourApp_$(appveyor_repo_tag_name)_windows_x86_64_portable.zip
    name: portable


deploy:
- provider: GitHub
  tag: $(appveyor_repo_tag_name)
  release: $(appveyor_repo_tag_name)
  description: $(appveyor_repo_tag_name)
  auth_token:
    secure: lNrwOGAylXafSwJAAwEbYBFGbpGjy7aYSCyAWl9jikP22ykJ1BqwKPKhKjo+f1JT
  prerelease: true
  artifact: portable
