environment:
  QBit_RELEASE_PATH: .
  - Qt: C:\Qt\5.9.1\msvc2017_64
    PLATFORM: amd64
    COMPILER: msvc
    VSVER: 14
    
install:
  - git submodule update --init --recursive

init:
  - set TAG_NAME=%APPVEYOR_REPO_TAG_NAME%

build_script:
  - call "scripts/build_windows.cmd"

  
artifacts:
  - path: build\windows\msvc\x86_64\release\QBit(appveyor_repo_tag_name)_windows_x86_64_portable.zip
    name: portable

deploy:
- provider: GitHub
  auth_token:
    secure: lNrwOGAylXafSwJAAwEbYBFGbpGjy7aYSCyAWl9jikP22ykJ1BqwKPKhKjo+f1JT
  prerelease: true
