environment:

    matrix:
    # MSVC x64
        - name: win64
        - platform: amd64
        - qt: 5.9\msvc2015_64
        - suffix: msvc2015

  # MinGW
        - name: win32
        - platform: mingw
        - qt: 5.9\mingw53_32
        - suffix: mingw
    
    
init:
  - if %platform%==mingw set PATH=%PATH:C:\Program Files\Git\usr\bin;=%
  - if %platform%==mingw set PATH=C:\Qt\Tools\mingw530_32\bin;%PATH%
  - set PATH=C:\Qt\%qt%\bin;%PATH%
  - if not %platform%==mingw call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" %platform%
  - if not %platform%==mingw (set makefiles="NMake Makefiles") else (set makefiles="MinGW Makefiles")
  - if %APPVEYOR_REPO_TAG%==true (set nogitinfo=ON) else (set nogitinfo=OFF)
  - set TAG_NAME=%APPVEYOR_REPO_TAG_NAME%
  
install:
  - git submodule update --init --recursive

build_script:
  - call "scripts/build_windows.cmd"

  
artifacts:
  - path: build\windows\msvc\x86_64\release\QBit(appveyor_repo_tag_name)_windows_x86_64_portable.zip
    name: portable

deploy:
- provider: GitHub
  auth_token:
    secure: lNrwOGAylXafSwJAAwEbYBFGbpGjy7aYSCyAWl9jikP22ykJ1BqwKPKhKjo+f1JT
  prerelease: true
