name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true
    - name: Update Modules
      run: cd external/libpeakpick && git submodule init && git submodule update --recursive
    - name: Install Qt
      uses: jurplel/install-qt-action@v2
    - name: configure
      run: mkdir build && cd build && cmake -DCMAKE_CXX_FLAGS="-Werror" ..
    - name: build
      run: cmake --build build
